[mongodb]
mongodb-dev.avyunan.fun

[catalogue]
catalogue-dev.avyunan.fun

[redis]
redis-dev.avyunan.fun

[mysql]
mysql-dev.avyunan.fun

[cart]
cart-dev.avyunan.fun

[user]
user-dev.avyunan.fun

[shipping]
shipping-dev.avyunan.fun

[rabbitmq]
rabbitmq-dev.avyunan.fun

[payment]
payment-dev.avyunan.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.avyunan.fun
CATALOGUE_HOST=catalogue-dev.avyunan.fun
REDIS_HOST=redis-dev.avyunan.fun
MY_SQL=mysql-dev.avyunan.fun
USER_HOST=user-dev.avyunan.fun
CART_HOST=cart-dev.avyunan.fun
SHIPPING_HOST=shipping-dev.avyunan.fun
RABBITMQ_HOST=rabbitmq-dev.avyunan.fun
PAYMENT_HOST=payment-dev.avyunan.fun


