[mongodb]
mongodb-dev.avyunan.fun

[catalogue]
catalogue-dev.avyunan.fun

[redis]
redis-dev.avyunan.fun

[mysql]
mysql-dev.avyunan.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.avyunan.fun
CATALOGUE_HOST=catalogue-dev.avyunan.fun
REDIS_HOST=redis-dev.avyunan.fun
MY_SQL=mysql-dev.avyunan.fun

